version: "3.9"

services:
  db:
    image: postgres:12.2-alpine
    container_name: "students-database"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - students-network
    volumes:
      - database_postgres:/var/lib/postgresql/data
  api:
    build: .
    container_name: "students-rest-api"
    environment:
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgres"
      DB_DB: "postgres"
      DB_HOST: "db"
      DB_TABLE: "postgres"
      DB_PORT: "5432"
    ports:
      - "9000:9000"
    depends_on:
      - db
    networks:
      - students-network

volumes:
  database_postgres:

networks:
  students-network:
    driver: bridge
